# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='profilePic',
            field=models.CharField(default='profile.png', max_length=140),
        ),
    ]
