# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160423_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviwer',
            new_name='reviewr',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
