# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160423_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewr',
            new_name='reviewer',
        ),
    ]
