# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_category_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_shortname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
