# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimage',
            name='imagefile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
