# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20160430_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pimage',
            old_name='imagefile',
            new_name='image',
        ),
        migrations.AddField(
            model_name='pimage',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
