# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160510_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='pimage',
            name='image',
            field=models.ImageField(upload_to='portfolio'),
        ),
    ]
