# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20160510_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='MEDIA_URL/profile.png', null=True, upload_to=''),
        ),
    ]
