# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20160513_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='MEDIA_ROOT/profile.png', null=True, upload_to=''),
        ),
    ]
