# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_account_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='pimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
